
version: "3"
services:
  web:
    build: ./client
    ports: 
      - "8000:3000"
    restart: always

  backend:
    build: ./server
    ports: 
      - "8001:8000"
    restart: always

  database:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports: 
      - "27017:27017"
    restart: always

