version: "3"
services:
  web:
    context: .
    build: ./client/Dockerfile
    ports: 8000:3000
    restart: always

  backend:
    context: .
    build: ./server/Dockerfile
    ports: 8001:8000
    restart: always

  database:
    image: mongodb
    enviroment:
      -MONGO_INITDB_ROOT_USERNAME: admin
      -MONGO_INITDB_ROOT_PASSWORD: secret
    volume: ./backup:/data/db
    ports: 27017:27017
    restart:always

    
    
	frontend:
		build: ./client/Dockerfile
		ports:
			-8080:8000
		networks:
			-devops
		restart: always


	backend:
		build: .server/Dockerfile
		ports:
			-8001:8000
		network:
			-devops
		depends_on:
			- "mongodb"			
		link:
			- "mongodb"
		deploy:
			resources:
			limits:
				cpus: 0.05
				memory: 50M
		restart: always


	mongodb:
		image: mongo
		enviroment:
			- "MONGO_INITDB_ROOT_USERNAME": admin
			- "MONGO_INITDB_ROOT_PASSWORD": secret
		volume: ./back:/data/db
		ports:
			-27017:27017
		networks:
			-devop
		restart:always


networks:
	devops:
		driver: bridge
